general:
  random_seed: 100
  directory_template: "b{ct}-{earc}-{darc}-{epc}"
  output_directory_template: "./models/{dir}"

logger:
  log_format: "(%(asctime)s) %(name)s [%(levelname)s]: %(message)s"
  log_file: "./logs/{dir}/seq2seq.log"
  log_level: "info"

export:
  csv:
    svc:
      - "Kernel"
      - "Nu"
      - "Gamma"
      - "F1"
    knc:
      - "Precision"
      - "Recall"
      - "F1"

data:
  reading:
    user_count: 40
    genuine_sample_count: 20
    forged_sample_count: 20
    signature_path_template: "./data_set/U{user}S{sample}.TXT"
    feature_count: 4

  reshaping:
    input_dimension: 14
    output_dimension: 14
    output_activation: "relu"
    sampling_step: 2
    window_size: 1
    window_step: 1

classifiers:
  reference_sample_count: 5
  train_user_count: 32
  test_user_count: 8
  knc:
    n_neighbors: 45

autoencoder:
  train:
    batch_size: 80
    epochs: 1000
    verbose: 1

  compile_config:
    loss: "mape"
    optimizer: "nadam"
    metrics:
      - "mae"
      - "mse"

  callbacks:
    early_stopping:
      monitor: "loss"
      min_delta: 0
      patience: 10
      verbose: 1
      mode: "auto"

  architecture:
    global: &global
      return_sequences: true
      implementation: 2
      activation: "relu"
      dropout: 0.2
      merge_mode: "concat"

    encoder:
      0:
        <<: *global
        go_backwards: true
        units: 200

    decoder:
      0:
        <<: *global
        units: 200

    cell_type: "LSTM"
